# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-12-08 17:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gooseroll',
            name='selected',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
