# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-12-09 00:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_auto_20161208_1728'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrizePoolItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prize', models.IntegerField(db_index=True)),
                ('description', models.CharField(max_length=256)),
            ],
        ),
    ]
